#!/bin/bash
# Git commit validator - enforces conventional commits and blocks AI footers.
#
# Input: git commit command string as $1
# Exit codes: 0=allow, 2=block, 1=error

set -uo pipefail

CMD="$1"

# --------------------------------------------------------------------------
# Extract commit message from -m flag (supports multiline bodies)
# --------------------------------------------------------------------------

MSG=""

# Heredoc: -m "$(cat <<'EOF' ... EOF)"
if [[ "$CMD" == *'-m "$(cat <<'* ]]; then
    # Extract between first line containing <<EOF and line containing EOF
    MSG=$(echo "$CMD" | sed -n '/<<.*EOF/,/^[[:space:]]*EOF/{/<<.*EOF/d;/^[[:space:]]*EOF/d;p}')
fi

# Double-quoted: -m "..." (pure bash, handles multiline)
if [[ -z "$MSG" && "$CMD" == *'-m "'* ]]; then
    local_tmp="${CMD#*-m \"}"
    MSG="${local_tmp%\"*}"
    # Verify extraction actually removed something (guards against no closing quote)
    [[ "$MSG" == "$local_tmp" ]] && MSG=""
fi

# Single-quoted: -m '...'
if [[ -z "$MSG" && "$CMD" == *"-m '"* ]]; then
    local_tmp="${CMD#*-m \'}"
    MSG="${local_tmp%\'*}"
    [[ "$MSG" == "$local_tmp" ]] && MSG=""
fi

# No -m flag (editor mode) — allow
[[ -z "$MSG" ]] && exit 0

# --------------------------------------------------------------------------
# Check for AI-generated footers
# --------------------------------------------------------------------------

if echo "$MSG" | grep -qEi 'Co-Authored-By:\s*Claude|Co-Authored-By:\s*.*@anthropic\.com|Generated by Claude|Generated by AI'; then
    echo "Git Commit Blocked: AI-generated footers not allowed. Remove Co-Authored-By: Claude lines." >&2
    exit 2
fi

# --------------------------------------------------------------------------
# Validate conventional commit format
# --------------------------------------------------------------------------

FIRST_LINE=$(echo "$MSG" | head -1)
TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"

if ! echo "$FIRST_LINE" | grep -qE "^($TYPES)(\(.+\))?!?:\s+.+"; then
    echo "Git Commit Blocked: Not conventional format. Use: <type>(<scope>): <subject>" >&2
    echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert" >&2
    exit 2
fi

exit 0
