#!/usr/bin/env python3
"""Git commit validator - enforces conventional commits and blocks AI footers.

Exit codes:
    0 - Allow command
    2 - Block command (stderr shown to model)
"""

import json
import re
import sys

# Conventional commit types
COMMIT_TYPES = [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "chore",
    "revert",
]

# Patterns that indicate AI-generated footers
AI_FOOTER_PATTERNS = [
    r"Co-Authored-By:\s*Claude",
    r"Co-Authored-By:\s*.*@anthropic\.com",
    r"Generated by Claude",
    r"Generated by AI",
]


def extract_commit_message(command: str) -> str | None:
    """Extract commit message from git commit command.

    Args:
        command: The git commit command string

    Returns:
        The commit message or None if not found
    """
    # Heredoc first - must check before simple pattern to avoid
    # matching the ' in <<'EOF' as a closing quote delimiter
    match = re.search(
        r'-m\s+"\$\(cat\s+<<[\'"]?EOF[\'"]?\s*\n(.+?)\nEOF', command, re.DOTALL
    )
    if match:
        return match.group(1)

    # Match -m "message" (including multiline bodies)
    match = re.search(r'-m\s+"((?:[^"\\]|\\.)+)"', command, re.DOTALL)
    if match:
        return match.group(1)

    # Match -m 'message' (including multiline bodies)
    match = re.search(r"-m\s+'((?:[^'\\]|\\.)+)'", command, re.DOTALL)
    if match:
        return match.group(1)

    return None


def validate_conventional_commit(message: str) -> tuple[bool, str]:
    """Validate commit message follows conventional commit format.

    Args:
        message: The commit message

    Returns:
        Tuple of (is_valid, error_message)
    """
    # Pattern: type(scope): subject or type: subject (! for breaking changes)
    pattern = rf"^({'|'.join(COMMIT_TYPES)})(\(.+?\))?!?:\s+.+"

    first_line = message.split("\n")[0].strip()

    if not re.match(pattern, first_line, re.IGNORECASE):
        types_str = ", ".join(COMMIT_TYPES)
        return (
            False,
            f"Not conventional format. Use: <type>(<scope>): <subject>\nTypes: {types_str}",
        )

    return True, ""


def check_ai_footer(message: str) -> tuple[bool, str]:
    """Check for AI-generated footers.

    Args:
        message: The commit message

    Returns:
        Tuple of (has_footer, pattern_matched)
    """
    for pattern in AI_FOOTER_PATTERNS:
        if re.search(pattern, message, re.IGNORECASE):
            return True, pattern

    return False, ""


def validate_git_commit(command: str) -> tuple[bool, str]:
    """Validate git commit command.

    Args:
        command: The git commit command string

    Returns:
        Tuple of (is_valid, error_message)
    """
    message = extract_commit_message(command)

    if not message:
        # No -m flag, might be opening editor - allow
        return True, ""

    # Check for AI footers
    has_footer, _ = check_ai_footer(message)
    if has_footer:
        return (
            False,
            "AI-generated footers not allowed. Remove Co-Authored-By: Claude lines.",
        )

    # Validate conventional commit format
    is_valid, error = validate_conventional_commit(message)
    if not is_valid:
        return False, error

    return True, ""


def main() -> int:
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Invalid JSON input: {e}", file=sys.stderr)
        return 1

    command = input_data.get("tool_input", {}).get("command", "")

    is_valid, error = validate_git_commit(command)

    if not is_valid:
        print(f"Git Commit Blocked: {error}", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
